name: learn-github-actions
on: [push]
jobs:
    build-library:
        runs-on: [self-hosted, Linux, X64]
        # Set critical environmental variables for CMake
        # configuring.
        env:
            MOUSEION_TOP_LEVEL: ${GITHUB_WORKSPACE}
            MOUSEION_CMAKE_CXX_COMPILER: mpiCC
            MOUSEION_CMAKE_C_COMPILER: mpicc
            MOUSEION_INSTALL_PREFIX: ${GITHUB_WORKSPACE}/sw
            MOUSEION_INSTALL_BIN_DIRECTORY: ${GITHUB_WORKSPACE}/sw/bin
            MOUSEION_INSTALL_INCLUDE_DIRECTORY: ${GITHUB_WORKSPACE}/sw/include
            MOUSEION_INSTALL_LIB_DIRECTORY: ${GITHUB_WORKSPACE}/sw/lib
            MOUSEION_BOOST_TOP_LEVEL: /opt/sw/boost/boost_1_72_0
            MOUSEION_MINIMUM_CMAKE_VERSION: 3.16
        # We always default to the bash shell. 
        defaults: 
            run:
                shell: bash
        steps:
            - name: Clone source
              uses: actions/checkout@v2
            - name: Build Mouseion library
              run: |
                module load openmpi/4.0.3
                module load boost/1.72
                export MOUSEION_BOOST_TOP_LEVEL=${BOOST_TOP_LEVEL} 
                echo "GITHUB_WORKSPACE = ${GITHUB_WORKSPACE}"
                echo "MOUSEION_TOP_LEVEL = " ${{ env.MOUSEION_TOP_LEVEL }}
                echo "MOUSEION_CMAKE_CXX_COMPILER = " ${{ env.MOUSEION_CMAKE_CXX_COMPILER }}
                echo "MOUSEION_CMAKE_C_COMPILER = " ${{ env.MOUSEION_CMAKE_C_COMPILER }}
                echo "MOUSEION_INSTALL_PREFIX = " ${{ env.MOUSEION_INSTALL_PREFIX }}
                echo "MOUSEION_INSTALL_BIN_DIRECTORY = " ${{ env.MOUSEION_INSTALL_BIN_DIRECTORY }}
                echo "MOUSEION_INSTALL_INCLUDE_DIRECTORY = " ${{ env.MOUSEION_INSTALL_INCLUDE_DIRECTORY }}
                echo "MOUSEION_INSTALL_LIB_DIRECTORY = " ${{ env.MOUSEION_INSTALL_LIB_DIRECTORY }}
                echo "MOUSEION_BOOST_TOP_LEVEL (1) = " ${{ env.MOUSEION_BOOST_TOP_LEVEL }}
                echo "MOUSEION_BOOST_TOP_LEVEL (2) = " ${BOOST_TOP_LEVEL}
                mkdir mouseion_cmake_build
                cd mouseion_cmake_build
                cmake -S ${GITHUB_WORKSPACE}
              env:
                  MOUSEION_BOOST_TOP_LEVEL: ${BOOST_TOP_LEVEL} 
