name: learn-github-actions
on: [push]
jobs:
    check-communicator:
        runs-on: [self-hosted, Linux, X64]
        env:
            MOUSEION_TOP_LEVEL=${GITHUB_WORKSPACE}
        defaults: 
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v2
            - run: |
                echo "Running communicator test: ${MOUSEION_TOP_LEVEL}"
                module load openmpi/4.0.3
                module load boost/1.72
            - run: module list

