name: learn-github-actions
on: [push]
jobs:
    check-communicator:
        runs-on: [self-hosted, Linux, X64]
        defaults: 
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v2
            - name: Checkout submodules
                run: git submodule update --init --recursive

